PIT/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Już jest stworzone konto na tym e-mailu, spróbuj innego')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToOne(mappedBy: 'User', targetEntity: "PersonDetail", cascade: ['remove'])]
    private ?PersonDetail $Person_detail_id = null;

    #[ORM\OneToOne(mappedBy: 'User_id', targetEntity: "Spouse", cascade: ['remove'])]
    private ?Spouse $Spouse_id = null;

    #[ORM\OneToOne(mappedBy: 'User_id', targetEntity: "Children", cascade: ['remove'])]
    private ?Children $Children_id = null;

    #[ORM\ManyToOne(inversedBy: 'User')]
    private ?PIT0 $pIT0 = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PIT0::class)]
    private Collection $pit0;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PIT37::class)]
    private Collection $pit37;

    public function __construct()
    {
        $this->pit0 = new ArrayCollection();
        $this->pit37 = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPersonDetailId(): ?PersonDetail
    {
        return $this->Person_detail_id;
    }

    public function setPersonDetailId(?PersonDetail $Person_detail_id): self
    {
        // unset the owning side of the relation if necessary
        if ($Person_detail_id === null && $this->Person_detail_id !== null) {
            $this->Person_detail_id->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($Person_detail_id !== null && $Person_detail_id->getUser() !== $this) {
            $Person_detail_id->setUser($this);
        }

        $this->Person_detail_id = $Person_detail_id;

        return $this;
    }

    public function getSpouseId(): ?Spouse
    {
        return $this->Spouse_id;
    }

    public function setSpouseId(?Spouse $Spouse_id): self
    {
        // unset the owning side of the relation if necessary
        if ($Spouse_id === null && $this->Spouse_id !== null) {
            $this->Spouse_id->setUserId(null);
        }

        // set the owning side of the relation if necessary
        if ($Spouse_id !== null && $Spouse_id->getUserId() !== $this) {
            $Spouse_id->setUserId($this);
        }

        $this->Spouse_id = $Spouse_id;

        return $this;
    }

    public function getChildrenId(): ?Children
    {
        return $this->Children_id;
    }

    public function setChildrenId(?Children $Children_id): self
    {
        // unset the owning side of the relation if necessary
        if ($Children_id === null && $this->Children_id !== null) {
            $this->Children_id->setUserId(null);
        }

        // set the owning side of the relation if necessary
        if ($Children_id !== null && $Children_id->getUserId() !== $this) {
            $Children_id->setUserId($this);
        }

        $this->Children_id = $Children_id;

        return $this;
    }

    public function getPIT0(): ?PIT0
    {
        return $this->pIT0;
    }

    public function setPIT0(?PIT0 $pIT0): self
    {
        $this->pIT0 = $pIT0;

        return $this;
    }

    public function addPit0(PIT0 $pit0): self
    {
        if (!$this->pit0->contains($pit0)) {
            $this->pit0->add($pit0);
            $pit0->setUser($this);
        }

        return $this;
    }

    public function removePit0(PIT0 $pit0): self
    {
        if ($this->pit0->removeElement($pit0)) {
            // set the owning side to null (unless already changed)
            if ($pit0->getUser() === $this) {
                $pit0->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PIT37>
     */
    public function getPit37(): Collection
    {
        return $this->pit37;
    }

    public function addPit37(PIT37 $pit37): self
    {
        if (!$this->pit37->contains($pit37)) {
            $this->pit37->add($pit37);
            $pit37->setUser($this);
        }

        return $this;
    }

    public function removePit37(PIT37 $pit37): self
    {
        if ($this->pit37->removeElement($pit37)) {
            // set the owning side to null (unless already changed)
            if ($pit37->getUser() === $this) {
                $pit37->setUser(null);
            }
        }

        return $this;
    }
}

PIT/templates/person/person.detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Person_detail_form{% endblock %}

{% block body %}
    {% include('base.html.twig') %}
    <section class="vh-200" style="background-color: #2779e2;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-9">
                    <h1 class="text-white mb-4">Wprowadź dane osobowe</h1>
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body">
                            <form action="/person_detail" method="post" >
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Imię</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="name" name="name" class="form-control " placeholder="Wprowadź imię">

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Nazwisko</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control " type="text" id="surname" name="surname" placeholder="Wprowadź nazwisko"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">PESEL</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="pesel" name="pesel" pattern="[0-9]{11}" title="Numer PESEL musi składać się tylko z cyfr i mieć długość 11 znaków." placeholder="Wprowadź PESEL" required><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Data urodzenia</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="date" id="birth_date" name="birth_date" placeholder="Wprowadź Data urodzenia"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Kraj</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="country" name="country" placeholder="Wprowadź Kraj"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Województwo</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="voivodeship" name="voivodeship" placeholder="Wprowadź Województwo"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Miasto</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="town" name="town" placeholder="Wprowadź Miasto"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Gmina</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="commune" name="commune" placeholder="Wprowadź Gmina"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Powiat</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="county" name="county" placeholder="Wprowadź Powiat"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Ulica</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="street" name="street" placeholder="Wprowadź Ulica"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Numer domu</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="house_number" name="house_number" placeholder="Wprowadź Numer domu"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Numer lokalu</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="apartment_number" name="apartment_number" placeholder="Wprowadź Numer lokalu"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Kod pocztowy</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="zip_code" name="zip_code" placeholder="Wprowadź Kod pocztowy"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="px-5 py-4">
                                    <button type="submit" class="btn btn-primary" value="Wyślij" href="/user" >Zatwierdź</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <script>
        document.querySelector("#pesel").addEventListener("change", function(event) {
            var pesel = event.target.value;
            var peselRegex = /^[0-9]{11}$/;
            var errorDiv = document.createElement("div");
            errorDiv.classList.add("error");
            errorDiv.innerText = "Numer PESEL musi składać się tylko z cyfr i mieć długość 11 znaków.";
            if (!peselRegex.test(pesel)) {
                document.querySelector("#pesel").after(errorDiv);
            } else {
                document.querySelector(".error").remove();
            }
        });


    </script>
{% endblock %}

PIT/templates/person/spouse.detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Spouse_detail_form{% endblock %}

{% block body %}
    {% include('base.html.twig') %}
    <section class="vh-200" style="background-color: #2779e2;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-9">
                    <h1 class="text-white mb-4">Wprowadź dane osobowe</h1>
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body">
                            <form action="/spouse_detail" method="post" >
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Imię</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="name" name="name" class="form-control " placeholder="Wprowadź imię">

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Nazwisko</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control " type="text" id="surname" name="surname" placeholder="Wprowadź nazwisko"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">PESEL</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="pesel" name="pesel" pattern="[0-9]{11}" title="Numer PESEL musi składać się tylko z cyfr i mieć długość 11 znaków." placeholder="Wprowadź PESEL" required><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Data urodzenia</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="date" id="birth_date" name="birth_date" placeholder="Wprowadź Data urodzenia"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Kraj</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="country" name="country" placeholder="Wprowadź Kraj"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Województwo</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="voivodeship" name="voivodeship" placeholder="Wprowadź Województwo"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Miasto</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="town" name="town" placeholder="Wprowadź Miasto"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Gmina</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="commune" name="commune" placeholder="Wprowadź Gmina"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Powiat</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="county" name="county" placeholder="Wprowadź Powiat"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Ulica</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="street" name="street" placeholder="Wprowadź Ulica"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Numer domu</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="house_number" name="house_number" placeholder="Wprowadź Numer domu"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Numer lokalu</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="apartment_number" name="apartment_number" placeholder="Wprowadź Numer lokalu"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Kod pocztowy</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control" type="text" id="zip_code" name="zip_code" placeholder="Wprowadź Kod pocztowy"><br>

                                    </div>
                                </div>
                                <hr class="mx-n3">
                                <div class="px-5 py-4">
                                    <button type="submit" class="btn btn-primary" value="Wyślij" href="/user" >Zatwierdź</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <script>
        document.querySelector("#pesel").addEventListener("change", function(event) {
            var pesel = event.target.value;
            var peselRegex = /^[0-9]{11}$/;
            var errorDiv = document.createElement("div");
            errorDiv.classList.add("error");
            errorDiv.innerText = "Numer PESEL musi składać się tylko z cyfr i mieć długość 11 znaków.";
            if (!peselRegex.test(pesel)) {
                document.querySelector("#pesel").after(errorDiv);
            } else {
                document.querySelector(".error").remove();
            }
        });


    </script>
{% endblock %}

PIT/templates/person/user.detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}User_detail{% endblock %}

{% block body %}
    {% include('base.html.twig') %}
    <section class="vh-100" style="background-color: #2779e2;">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="text-white mb-4">Informacje o użytkowniku</h2>
                    <div class="card">
                        <div class="card-body">
                            <p><strong>Imie:</strong> {{ personDetail.name|default('brak danych') }}</p>
                            <p><strong>Nazwisko:</strong> {{ personDetail.surname |default('brak danych') }}</p>
                            {#    <p><strong>Data urodzenia:</strong> {{ personDetail.birth_date|default('brak danych') }}</p>#}
                            <p><strong>PESEL:</strong> {{ personDetail.pesel |default('brak danych')  }}</p>
                            <p><strong>Kraj:</strong> {{ personDetail.country |default('brak danych') }}</p>
                            <p><strong>Województwo:</strong> {{ personDetail.voivodeship |default('brak danych') }}</p>
                            <p><strong>Miasto:</strong> {{ personDetail.town |default('brak danych') }}</p>
                            <p><strong>Gmina:</strong> {{ personDetail.commune |default('brak danych') }}</p>
                            <p><strong>Powiat:</strong> {{ personDetail.county |default('brak danych') }}</p>
                            <p><strong>Ulica:</strong> {{ personDetail.street |default('brak danych') }}</p>
                            <p><strong>Numer domu:</strong> {{ personDetail.housenumber |default('brak danych') }}</p>
                            <p><strong>Numer lokalu:</strong> {{ personDetail.apartmentnumber |default('brak danych') }}</p>
                            <p><strong>Kod pocztowy:</strong> {{ personDetail.zipcode |default('brak danych') }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="/person_detail_add" class="btn btn-primary">Uzupełnij dane osobowe</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h2 class="text-white mb-4">Informacje o współmałżonku</h2>
                    <div class="card">
                        <div class="card-body">
                            <p><strong>Imie:</strong> {{ spouseDetail.personDetailId.name|default('brak danych') }}</p>
                            <p><strong>Nazwisko:</strong> {{ spouseDetail.personDetailId.surname |default('brak danych') }}</p>
                            {#    <p><strong>Data urodzenia:</strong> {{ spouseDetail.personDetailId.birth_date|default('brak danych') }}</p>#}
                            <p><strong>PESEL:</strong> {{ spouseDetail.personDetailId.pesel |default('brak danych')  }}</p>
                            <p><strong>Kraj:</strong> {{ spouseDetail.personDetailId.country |default('brak danych') }}</p>
                            <p><strong>Województwo:</strong> {{ spouseDetail.personDetailId.voivodeship |default('brak danych') }}</p>
                            <p><strong>Miasto:</strong> {{ spouseDetail.personDetailId.town |default('brak danych') }}</p>
                            <p><strong>Gmina:</strong> {{ spouseDetail.personDetailId.commune |default('brak danych') }}</p>
                            <p><strong>Powiat:</strong> {{ spouseDetail.personDetailId.county |default('brak danych') }}</p>
                            <p><strong>Ulica:</strong> {{ spouseDetail.personDetailId.street |default('brak danych') }}</p>
                            <p><strong>Numer domu:</strong> {{ spouseDetail.personDetailId.housenumber |default('brak danych') }}</p>
                            <p><strong>Numer lokalu:</strong> {{ spouseDetail.personDetailId.apartmentnumber |default('brak danych') }}</p>
                            <p><strong>Kod pocztowy:</strong> {{ spouseDetail.personDetailId.zipcode |default('brak danych') }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="/spouse_detail_add" class="btn btn-primary">Dodaj Współmałżonka/Współmałżonkę</a>
{#                            <a href="#" class="btn btn-primary">Dodaj dziecko/dzieci</a>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <a class="btn btn-success" href="/pit-summary">Zobacz swój pit-37</a>
        </div>

    </section>
{% endblock %}